### ISSUE TITLE
What does your dev environment look like?

### ISSUE THREAD

**Issue by sindresorhus** [arnaudbenard/ama#6]
Editor, terminal, tools, themes, fonts, process, etc.

**Comment by arnaudbenard** [comment]
I use sublime text with the [One Dark](https://github.com/IceTimux/one-dark-sublime-text-3-color-scheme) theme and Source Code Pro. My terminal uses zsh with the cloud theme. I use a few tools like [Postico](https://eggerapps.at/postico/) and [Sketch](https://www.sketchapp.com/). I'm a big fan of using simple cli commands for building my apps and using `package.json` extensively.
