### ISSUE TITLE
How do you balance working and relaxing when traveling as a digital nomad?

### ISSUE THREAD

**Issue by sindresorhus** [arnaudbenard/ama#7]

**Comment by arnaudbenard** [comment]
The biggest trouble I have is that my work and leisure laptop is the same one, it's hard to completely disconnect from work. I try to make a list of the things I want to finish for the day to help me not going overboard. 

I still can't really work in planes and trains but I found that those places are good to read documentation and take time to understand new tech.

Taking time for relaxing is really important, I try to change my environment when I want to relax/work. For example I always work in coworking spaces or coffee places and never do work at home.
